import { firestore } from 'firebase';
import Head from 'next/head';
import Movimientos from '../components/Movimientos';
import { db } from '../firebase/client';

export default function Trade({userUid, tradeFb}) {

  // console.log(userUid)
   
    return (
        <>
            <Head>
                <title>Movimientos | Crypto</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className=" md:px-8 h-auto mt-10">
                <div className="container mx-auto max-w-full">
                    <div className="grid grid-cols-1 mb-16">
                        <Movimientos userUid={userUid} />
                    </div>
                </div>
            </div>
        </>
    );
}
export async function getServerSideProps(ctx) {

  // console.log('hola ' + ctx.req.cookies.token )

    // const resF = await firestore().collection(ctx.req.cookies.token).doc('movimientos').collection('order').get()
    // const docs = resF.docs.map((doc)=> ({...doc.data(),docId: doc.id}))

// console.log(docs)

  
    return {
      props: {
        // tradeFb: JSON.stringify(docs),
        userUid: ctx.req.cookies.token,
      }, // will be passed to the page component as props
    }
  }