import Head from 'next/head';
import TradeForm from '../components/TradeForm';

export default function Trade() {
    return (
        <>
            <Head>
                <title>Trade | Crypto</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <div className="md:px-8 h-auto mt-10">
                <div className="container mx-auto max-w-full">
                    <div className="grid grid-cols-1 mb-16">
                        <TradeForm />
                    </div>
                </div>
            </div>
        </>
    );
}
